#ifndef GMS_FILTER_ENUMS_H
#define GMS_FILTER_ENUMS_H

enum FILTER_COMPUTATION_TYPE
{
  FIR=0,
  IIR=1,
  AR=2,
  PM=3
};

typedef enum FILTER_COMPUTATION_TYPE FILTER_COMPUTATION_TYPE;

enum FILTER_DESIGN_MODEL
{
  BUTTERWORTH=0,
  CHEBYSHEV_I=1,
  CHEBYSHEV_II=2,
  ELLIPTIC=3
};

typedef enum FILTER_DESIGN_MODEL FILTER_DESIGN_MODEL;

enum FILTER_BAND_TYPE
{
  LOW_PASS=0,
  HIGH_PASS=1,
  BAND_PASS=2,
  BAND_REJECT=3
};

typedef enum FILTER_BAND_TYPE FILTER_BAND_TYPE;

enum FILTER_TYPE
{
    CASCADE=0,
    IIR_BUTTERWORTH=1,
    FIR_HAMMING=2,
    LINEAR_OTHER=3
};

typedef enum FILTER_TYPE FILTER_TYPE;

#endif