spring:
  application:
    name: signal-enhancement-configuration
  processing:
    configuration-names: signal-enhancement, signal-enhancement-configuration
  codec:
    max-in-memory-size: 20MB

server:
  compression:
    enabled: true
    mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/msgpack"
    min-response-size: 1024
  servlet:
    context-path: /signal-enhancement-configuration-service

gms:
  persistence:
    oracle:
      account: gms_global_ro
      unit: gms_station_definition
    
qcMaskPersistenceUnitName: gms_qc_mask
qcMaskDurationTimeConfig: qc-mask.qc-duration-time-parameters
qcMaskJdbcUrlConfig: qc-mask.jdbc_url

filterListDefinitionConfig: global.filter-list-definition
filterDefinitionsByUsageConfig: global.default-filter-definitions-by-usage
filterMetadataConfig: global.filter-metadata
processingMaskDefinitionConfig: global.processing-mask-definition

instrumentResponseDefinitionConfig: station-definition.frequency-amplitude-phase-definition

signalDetectionPersistenceUnitName: gms_signal_detection

monitoringOrgConfig: global.monitoring-org
accountsByStageConfig: global.stage-accounts
orderedStagesConfig: workflow-manager.workflow-definition
waveformLeadLagConfig: signal-detection.waveform-lead-lag
signalEnhancementBeamformingConfig: global.beamforming-configuration
fkReviewablePhasesConfig: global.fk-reviewable-phases
fkSpectraTemplatesConfig: global.fk-spectra-template-config

rotationTemplateConfig: signal-enhancement.rotation-template-config

signalEnhancementConfiguration:
  hostname: signal-enhancement-configuration-service
  contextPath: /signal-enhancement-configuration
  port: 8080
  urlPaths:
    filterDefsByUsageForSDHs: /default-filter-definitions-for-signal-detection-hypotheses

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    
logging:
  level:
    _org.springframework.web.servlet.HandlerMapping.Mappings: DEBUG