#ifndef FK_UNCERTAINTY_OPTION_H
#define FK_UNCERTAINTY_OPTION_H

enum class FkUncertaintyOption {
    EMPIRICAL = 0,
    EXPONENTIAL_SIGNAL_COHERENCE = 1,
    OBSERVED_SIGNAL_COHERENCE = 2,
    PERFECT_SIGNAL_COHERENCE = 3
};

#endif //FK_UNCERTAINTY_OPTION_H