spring:
  application:
    name: bridged-data-source-simulator
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
      org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,
      org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  processing:
    configuration-names: bridged-data-source-simulator
  codec:
    max-in-memory-size: 10MB
  jpa:
    open-in-view: false

server:
  compression:
    enabled: true
    mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/msgpack"
    min-response-size: 1024
  servlet:
    context-path: /bridged-data-source-simulator

gms:
  persistence:
    oracle:
      account: gms_global_ro