#ifndef DEPTH_RESTRAINT_REASON_H
#define DEPTH_RESTRAINT_REASON_H

enum class DepthRestraintReason {
    FIXED_AT_DEPTH_FOUND_USING_DEPTH_PHASE_MEASUREMENTS = 0,
    FIXED_AS_STANDARD_DEPTH = 1,
    FIXED_AT_SURFACE = 2,
    FIXED_BY_ANALYST = 3,
    OTHER = 4
};

#endif // DEPTH_RESTRAINT_REASON_H