#ifndef FEATURE_PREDICTION_COMPONENT_TYPE_H
#define FEATURE_PREDICTION_COMPONENT_TYPE_H

enum class FeaturePredictionComponentType {
    BASEMODEL_PREDICTION = 0,
    BULK_STATIC_STATION_CORRECTION = 1,
    ELEVATION_CORRECTION = 2,
    ELLIPTICITY_CORRECTION = 3,
    MASTER_EVENT_CORRECTION = 4,
    PATH_CORRECTION = 5,
    SOURCE_DEPENDENT_CORRECTION = 6,
    UNCERTAINTY_DISTANCE_DEPENDENT = 7,
    UNCERTAINTY_PATH_DEPENDENT = 8,
    UNCERTAINTY_STATION_PHASE_DEPENDENT = 9,
};

#endif // FEATURE_PREDICTION_COMPONENT_TYPE_H