#ifndef FEATURE_MEASUREMENT_TYPE_H
#define FEATURE_MEASUREMENT_TYPE_H

enum class FeatureMeasurementType {
    ARRIVAL_TIME = 0,
    EMERGENCE_ANGLE = 1,
    SOURCE_TO_RECEIVER_AZIMUTH = 2,
    RECEIVER_TO_SOURCE_AZIMUTH = 3,
    SLOWNESS = 4,
    SIGNAL_DURATION = 5,
    PHASE = 6,
    AMPLITUDE_A5_OVER_2 = 7,
    AMPLITUDE_ANL_OVER_2 = 8,
    AMPLITUDE_ALR_OVER_2 = 9,
    AMPLITUDE_A5_OVER_2_OR = 10,
    AMPLITUDE_ANP_OVER_2 = 11,
    AMPLITUDE_FKSNR = 12,
    AMPLITUDE_LRM0 = 13,
    AMPLITUDE_NOI_LRM0 = 14,
    AMPLITUDE_RMSAMP = 15,
    AMPLITUDE_SBSNR = 16,
    PERIOD = 17,
    RECTILINEARITY = 18,
    SNR = 19,
    LONG_PERIOD_FIRST_MOTION = 20,
    SHORT_PERIOD_FIRST_MOTION = 21,
    SOURCE_TO_RECEIVER_DISTANCE = 22,
    MAGNITUDE_CORRECTION = 23
};

#endif // FEATURE_MEASUREMENT_TYPE_H