#ifndef PROCESSING_OPERATION_H
#define PROCESSING_OPERATION_H
enum class ProcessingOperation{
    AMPLITUDE_MEASUREMENT_BEAM = 0,
    DISPLAY_FILTER = 1,
    EVENT_BEAM = 2,
    FK_BEAM = 3,
    FK_SPECTRA = 4,
    ROTATION = 5,
    SIGNAL_DETECTION_BEAM = 6,
    SPECTROGRAM = 7,
    VIRTUAL_BEAM = 8
};
#endif //PROCESSING_OPERATION_H