#ifndef UNITS_H
#define UNITS_H

enum class Units
{
  DEGREES = 0,
  DECIBELS = 1,
  RADIANS = 2,
  SECONDS = 3,
  HERTZ = 4,
  SECONDS_PER_DEGREE = 5,
  SECONDS_PER_RADIAN = 6,
  SECONDS_PER_DEGREE_SQUARED = 7,
  SECONDS_PER_KILOMETER_SQUARED = 8,
  SECONDS_PER_KILOMETER = 9,
  SECONDS_PER_KILOMETER_PER_DEGREE = 10,
  ONE_OVER_KM = 11,
  NANOMETERS = 12,
  NANOMETERS_PER_SECOND = 13,
  NANOMETERS_PER_COUNT = 14,
  NANOMETERS_SQUARED_PER_SECOND = 15,
  UNITLESS = 16,
  MAGNITUDE = 17,
  COUNTS_PER_NANOMETER = 18,
  COUNTS_PER_PASCAL = 19,
  PASCALS_PER_COUNT = 20
};

#endif //UNITS_H