#ifndef GMS_BEAM_ENUMS_H
#define GMS_BEAM_ENUMS_H

enum SAMPLING_TYPE
{
    INTERPOLATED=0,
    NEAREST_SAMPLE=1
};

typedef enum SAMPLING_TYPE SAMPLING_TYPE;

enum BEAM_SUMMATION_TYPE
{
    COHERENT=0,
    INCOHERENT=1,
    RMS=2
};

typedef enum BEAM_SUMMATION_TYPE BEAM_SUMMATION_TYPE;

enum BEAM_TYPE
{
    AMPLITUDE=0,
    CONTINUOUS_LOCATION=1,
    DETECTION=2,
    EVENT=3,
    FK=4
};

typedef enum BEAM_TYPE BEAM_TYPE;

#endif // GMS_BEAM_ENUMS_H