SUBDIRS := builder \
           fluentd \
           keycloak \
           keycloak-postgresql \
           minio \
           postgres \
           ubi

include $(shell CI-MAKE-CONFIG-PATH)/Makefile.subdir
