# gms-sysconfig specific environment
# Any dependencies added here should also be added to the combined environment file in python/gms-test-environment.yml
#
# After making any changes to this file, a clean gms-sysconfig environment needs to be created, and the lock file regenerated:
# Run the script:
# ./create-python-lock.sh
#

name: gms-sysconfig
channels:
  - conda-forge
dependencies:
  - jproperties=2.1.1
  - pip=23.3.2
  - python=3.10.13
  - pip:
    - etcd3==0.12.0
    - grpcio==1.44.0  # https://github.com/grpc/grpc/issues/29643
