---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-ports-config
  annotations:
    "helm.sh/resource-policy": keep
data:
  base_domain: {{ .Values.ingress.baseDomain | quote }}
  istio_port: {{ .Values.ingress.istioPort | quote }}
  nginx_port: {{ .Values.ingress.nginxPort | quote }}
