---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bridge-path-config
  annotations:
    "helm.sh/resource-policy": keep
data:
  bridge-responses: {{ .Values.bridgePath.responses | quote }}
  bridge-responses-mount: {{ .Values.bridgePath.responsesMount | quote }}
  bridge-waveforms: {{ .Values.bridgePath.waveforms | quote }}
  bridge-waveforms-mount: {{ .Values.bridgePath.waveformsMount | quote }}
