---
{{/* install directly into istio-system namespace if it exists */}}
{{- if (lookup "v1" "Namespace" "" "istio-system") }}
apiVersion: v1
kind: Secret
metadata:
  name: ingress-default-cert
  namespace: istio-system
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.wildcardCrt | b64enc }}
  tls.key: {{ .Values.ingress.wildcardKey | b64enc }}
{{- end }}
