---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-default-cert
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.wildcardCrt | b64enc }}
  tls.key: {{ .Values.ingress.wildcardKey | b64enc }}
