parserOptions:
  project: './tsconfig-build.json'
extends:
  - '../../.eslintrc.yaml'
settings:
  import/resolver:
    node:
      extensions: ['.ts', '.tsx', '.js']
      moduleDirectory:
        - 'node_modules'
    typescript:
      alwaysTryTypes: true
      project:
        - tsconfig-build.json
    eslint-import-resolver-custom-alias:
      alias:
        # alias for ui-app package
        '~analyst-ui': 'src/ts/components/analyst-ui'
        '~app': 'src/ts/app'
        '~config': 'src/ts/config'
        '~env': 'src/ts/env'
        '~common-ui': 'src/ts/components/common-ui'
        '~components': 'src/ts/components'
        '~css': 'src/css'
        '~resources': 'src/ts/resources'
        '~scss-config': 'src/ts/scss-config'
      extensions:
        - '.ts'
        - '.tsx'
        - '.js'
        - '.scss'
      packages:
        - ''
