#ifndef GMS_FK_ENUMS_H
#define GMS_FK_ENUMS_H

enum FK_UNCERTAINTY_OPTION
{
    EMPIRICAL=0,
    EXPONENTIAL_SIGNAL_COHERENCE=1,
    OBSERVED_SIGNAL_COHERENCE=2,
    PERFECT_SIGNAL_COHERENCE=3
};

typedef enum FK_UNCERTAINTY_OPTION FK_UNCERTAINTY_OPTION;

#endif