#ifndef GMS_COMMON_ENUMS_H
#define GMS_COMMON_ENUMS_H

enum RETURN_CODE
{
    SUCCESS=0,
    INVALID_BOUNDS=1,
    INSUFFICIENT_DATA=2,
    INVALID_CONFIGURATION=3,
    MEMORY_ALLOCATION_ERROR=4,
    NOT_YET_IMPLEMENTED=5
};
typedef enum RETURN_CODE RETURN_CODE;

enum UNITS
{
    DEGREES=0,
    DECIBELS=1,
    RADIANS=2,
    SECONDS=3,
    HERTZ=4,
    KILOMETERS=5,
    KILOMETERS_PER_SECOND=6,
    SECONDS_PER_DEGREE=7,
    SECONDS_PER_RADIAN=8,
    SECONDS_PER_DEGREE_SQUARED=9,
    SECONDS_PER_KILOMETER_SQUARED=10,
    SECONDS_PER_KILOMETER=11,
    SECONDS_PER_KILOMETER_PER_DEGREE=12,
    ONE_OVER_KM=13,
    NANOMETERS=14,
    NANOMETERS_PER_SECOND=15,
    NANOMETERS_SQUARED_PER_SECOND=16,
    NANOMETERS_PER_COUNT=17,
    LOG_NM=18,
    UNITLESS=19,
    COUNTS_PER_NANOMETER=20,
    COUNTS_PER_PASCAL=21,
    PASCALS_PER_COUNT=22,
    PASCALS=23,
    MICROPASCALS=24
};
typedef enum UNITS UNITS;

enum TAPER_FUNCTION
{
    BLACKMAN=0,
    COSINE=1,
    HAMMING=2,
    HANNING=3,
    PARZEN=4,
    WELCH=5
};
typedef enum TAPER_FUNCTION TAPER_FUNCTION;

enum TAPER_DIRECTION
{
    FORWARD=0,
    REVERSE=1,
    BOTH=2
};
typedef enum TAPER_DIRECTION TAPER_DIRECTION;

enum FIX_TYPE
{
    ZERO=0,
    INTERPOLATE=1
};
typedef enum FIX_TYPE FIX_TYPE;

enum PROCESSING_OPERATION
{
    AMPLITUDE_MEASUREMENT=0,
    DISPLAY_FILTER=1,
    EVENT_BEAM=2,
    FK_BEAM=3,
    FK_SPECTRA=4,
    ROTATION=5,
    SIGNAL_DETECTION_BEAM=6,
    SPECTROGRAM=7,
    VIRTUAL_BEAM=8
};
typedef enum PROCESSING_OPERATION PROCESSING_OPERATION;

enum QC_SEGMENT_TYPE
{
    AGGREGATE=0,
    CALIBRATION=1,
    FLAT=2,
    GAP=3,
    NOISY=4,
    SENSOR_PROBLEM=5,
    SPIKE=6,
    STATION_PROBLEM=7,
    STATION_SECURITY=8,
    TIMING=9
};
typedef enum QC_SEGMENT_TYPE QC_SEGMENT_TYPE;
#endif // GMS_COMMON_ENUMS_H